// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMado5yoPjaSO5_5Wj9WFy7jyUggyjubY',
    appId: '1:940841038263:web:ceaaec38e22b6550793832',
    messagingSenderId: '940841038263',
    projectId: 'gdgsfax-79949',
    authDomain: 'gdgsfax-79949.firebaseapp.com',
    storageBucket: 'gdgsfax-79949.appspot.com',
    measurementId: 'G-TLYDW38B25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLH9Eu2ZaOmnqnaElsVD6tPTyekTZ_10A',
    appId: '1:940841038263:android:0573ed3fe8363250793832',
    messagingSenderId: '940841038263',
    projectId: 'gdgsfax-79949',
    storageBucket: 'gdgsfax-79949.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBka73TpQnF6Fy8-15TJFGohXDXPAbFu_U',
    appId: '1:940841038263:ios:9e90a6c25ffd8839793832',
    messagingSenderId: '940841038263',
    projectId: 'gdgsfax-79949',
    storageBucket: 'gdgsfax-79949.appspot.com',
    iosBundleId: 'com.example.gdgSfax',
  );
}
