// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3Xkeb97S2e56ADcozcB5l-DsdioTFsis',
    appId: '1:348770220404:web:bde4b2c42f0ff008951421',
    messagingSenderId: '348770220404',
    projectId: 'gdg-sfax-01',
    authDomain: 'gdg-sfax-01.firebaseapp.com',
    storageBucket: 'gdg-sfax-01.appspot.com',
    measurementId: 'G-T4LNM9BM2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Fo8rcyUBTzvoSvB9t66u41TxSLdJ3EE',
    appId: '1:348770220404:android:17fafa5dcda780a5951421',
    messagingSenderId: '348770220404',
    projectId: 'gdg-sfax-01',
    storageBucket: 'gdg-sfax-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSpsxbq3IlRU5ti11IXECOlztzvidTyy4',
    appId: '1:348770220404:ios:b7881be28f85ed33951421',
    messagingSenderId: '348770220404',
    projectId: 'gdg-sfax-01',
    storageBucket: 'gdg-sfax-01.appspot.com',
    iosBundleId: 'com.example.gdgSfax',
  );
}
